### ISSUE TITLE
missing chromaprint.h:

### ISSUE THREAD

**Issue by ItsFunny** [go-fingerprint/gochroma#4]
fatal error: chromaprint.h: No such file or directory

i have installed the ffmpeg(version 4.8) and fftw (3.3.8)

**Comment by krjackvinator** [comment]
Hi,
Please make sure that you have installed the `chromaprint` library as well. You can build it from source (https://github.com/acoustid/chromaprint) or install via package manager, e.g. `brew install chromaprint` for OS X

**Comment by ItsFunny** [comment]
thx ,i change the os from cenots7 to ubuntu ,its doesnt happen again ,but it occured new issue ,do u have any idea of this ' could not determine kind of name for C.uint32_t' 
i search the google ,and i found maybe its a solutaion: [link](https://github.com/mkb218/gosndfile/issues/13)
